### ISSUE TITLE
SDK Customisation

### ISSUE THREAD

**Issue by revibeali** [Shopify/checkout-sheet-kit-react-native#90]
### What area is the issue related to?

Checkout Sheet Kit

### What platform does the issue affect?

All platforms

### What version of `@shopify/checkout-sheet-kit` are you using?

2.0.1

### Steps to Reproduce

I am basically confused in 2 different topics: 
1. How exactly we can integrate this SDK for a Flutter app? 
2. Can we add some validations to the checkout, like phone number format validations, show some UI extensions - the way we  can do on website through checkout extensibility apps? 

### Expected Behavior

General Question

### Actual Behavior

General Question

### Storefront domain

revibe-me.myshopify.com

**Comment by markmur** [comment]
Hi @revibeali, 

We don't offer official support for a Flutter SDK. This library implements a Native Module to bridge from React Native to our native [Android](https://github.com/Shopify/checkout-sheet-kit-android) and [Swift](https://github.com/Shopify/checkout-sheet-kit-android) Checkout Sheet Kits.

Integrating the Checkout Sheet Kit with Flutter would require writing a bridge similar to the one in this repo, but specifically for Flutter. See [here](https://github.com/Shopify/checkout-sheet-kit-react-native/blob/main/modules/%40shopify/checkout-sheet-kit/ios/ShopifyCheckoutSheetKit.swift) for the Swift implementation and [here](https://github.com/Shopify/checkout-sheet-kit-react-native/blob/main/modules/%40shopify/checkout-sheet-kit/android/src/main/java/com/shopify/reactnative/checkoutsheetkit/ShopifyCheckoutSheetKitModule.java) for the Android implementation. Flutter support is on our radar, but not something we have commit to supporting just yet.

To your second question regarding extensions; any checkout extensions present on your web checkout will also show up in the in the mobile experience. We don't currently offer any way to customize for one and not the other.

Hope this helps!

Since this issue is unrelated to the react native repo itself, I'm going to close the issue, but happy to answer any more questions your might have.
